services:
  - type: web
    name: review-sentiment-analysis  # Service name should be unique
    env: python
    plan: free
    buildCommand: ./setup.sh && pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 1200
    autoDeploy: true
    envVars:
      - key: MYSQL_HOST
        value: ${MYSQL_HOST}
      - key: MYSQL_USER
        value: ${MYSQL_USER}
      - key: MYSQL_PASSWORD
        value: ${MYSQL_PASSWORD}
      - key: MYSQL_DB
        value: ${MYSQL_DB}
