services:
  - type: web
    name: review-sentiment-analysis
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    autoDeploy: true
    envVars:
      - key: MYSQL_HOST
        fromDatabase:
          name: your-database-name
          property: host
      - key: MYSQL_USER
        fromDatabase:
          name: your-database-name
          property: user
      - key: MYSQL_PASSWORD
        fromDatabase:
          name: your-database-name
          property: password
      - key: MYSQL_DB
        fromDatabase:
          name: your-database-name
          property: database
